services:
  - type: web
    name: chatbot-rag
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn chat_api:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: GOOGLE_API_KEY
        sync: false
      - key: PORT
        value: 10000 